### ISSUE TITLE
Possible improvements for some non-standard address formats

### ISSUE THREAD

**Issue by rossj** [andris9/addressparser#7]
Hello,
I'm processing an email dump of many thousand emails, many of which seem to contain addresses that appear to be in a non-standard format. I'm curious if you have seen such formats before, and if you have any suggestions for handling them. If you think `addressparser` should support such formats, I could try to work on a PR.

Here is an example of the type of `To` header I'm talking about:

````
To: 'John Doe'; 'janesmith@domain.com'; Bob Jones (bjones@domain.com); Shmoe, Joe; Kelly Johnson
````

The current output from this module is:

````
[
  {
    "address": "",
    "name": "'John Doe'"
  },
  {
    "address": "'janesmith@domain.com'",
    "name": ""
  },
  {
    "address": "",
    "name": "Bob Jones"
  },
  {
    "address": "",
    "name": "Shmoe"
  },
  {
    "address": "",
    "name": "Joe"
  },
  {
    "address": "",
    "name": "Kelly Johnson"
  }
]
````

Ideally, the output would be as follows:
````
[
  {
    "address": "",
    "name": "John Doe"
  },
  {
    "address": "janesmith@domain.com",
    "name": ""
  },
  {
    "address": "bjones@domain.com",
    "name": "Bob Jones"
  },
  {
    "address": "",
    "name": "Shmoe, Joe"
  },
  {
    "address": "",
    "name": "Kelly Johnson"
  }
]
````

I'm not sure how common such address headers are out in the wild... I believe these emails were exported using software called OUTLOOK2MAC, but I'm not 100% sure. Apart from the address headers, the rest of the email format seems to be fine.

**Comment by andris9** [comment]
I understand the problem but this input is way too vague, this module is too simplistic to do some kind of heuristics and stuff to figure out the meaning of values. 

This isn't supported by "normal" e-mail clients as well. For example this is what the OSX Mail app thinks of such `To:` value:

\ | Name | Address
---|---------|-----------
1 | bjones@domain.com | John Doe'; 'janesmith@domain.com'; Bob Jones ; Shmoe
2 | Joe; Kelly Johnson | Joe; Kelly Johnson
